In [1]:
import pandas as pd
import numpy as np #Permite trabajar con matriz y otras cosas de datos

In [2]:
#Ejercicio 6
Super = pd.read_csv("supermarket_sales.csv") 
Super

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
0,253-12-6086,A,Yangon,Member,Female,Sports and travel,98.40,7,34.4400,$723.24,8.7,Credit card,03/12/2019,12:43:00 p. m.,688.80,4.761905,34.4400
1,276-54-0879,B,Mandalay,Normal,Male,Sports and travel,97.74,4,19.5480,$410.51,6.4,Ewallet,03/12/2019,07:53:00 p. m.,390.96,4.761905,19.5480
2,373-14-0504,A,Yangon,Member,Female,Sports and travel,71.63,2,7.1630,$150.42,8.8,Ewallet,02/12/2019,02:33:00 p. m.,143.26,4.761905,7.1630
3,659-36-1684,C,Naypyitaw,Member,Male,Sports and travel,57.12,7,19.9920,$419.83,6.5,Credit card,01/12/2019,12:02:00 p. m.,399.84,4.761905,19.9920
4,751-15-6198,B,Mandalay,Normal,Male,Sports and travel,23.01,6,6.9030,$144.96,7.9,Ewallet,01/12/2019,04:45:00 p. m.,138.06,4.761905,6.9030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,811-03-8790,A,Naypyitaw,Normal,Female,Electronic accessories,45.48,10,22.7400,$477.54,4.8,Credit card,03/01/2019,10:22:00 a. m.,454.80,4.761905,22.7400
1006,551-21-3069,C,Naypyitaw,Normal,Female,Electronic accessories,23.07,9,10.3815,218.0115,4.9,Cash,02/01/2019,11:27:00 a. m.,207.63,4.761905,10.3815
1007,416-17-9926,A,Naypyitaw,Member,Female,Electronic accessories,74.22,10,37.1100,$779.31,4.3,Credit card,01/01/2019,02:42:00 p. m.,742.20,4.761905,37.1100
1008,556-97-7101,C,Naypyitaw,Normal,Female,Electronic accessories,63.22,2,6.3220,132.762,8.5,Cash,01/01/2019,03:51:00 p. m.,126.44,4.761905,6.3220
1009,891-01-7034,B,Naypyitaw,Normal,Female,Electronic accessories,74.71,6,22.4130,470.673,6.7,Cash,01/01/2019,07:07:00 p. m.,448.26,4.761905,22.4130

In [25]:
#Ejercicio 7
consulta2 = Super[(((Super["City"]) == "Yangon")
                 & ((Super["Gender"]) == "Male")
                 & ((Super["Product line"]) == "Sports and travel")
                 &((Super["Payment"]) == "Credit card"))]
consulta2

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
8,289-15-7034,A,Yangon,Member,Male,Sports and travel,82.33,4,16.4660,$345.79,7.5,Credit card,01/11/2019,10:37:00 a. m.,329.32,4.761905,16.4660
34,541-48-8554,A,Yangon,Normal,Male,Sports and travel,60.95,9,27.4275,$575.98,6.0,Credit card,01/07/2019,12:08:00 p. m.,548.55,4.761905,27.4275
36,199-75-8169,A,Yangon,Member,Male,Sports and travel,15.81,10,7.9050,$166.01,8.6,Credit card,03/06/2019,12:27:00 p. m.,158.10,4.761905,7.9050
57,550-84-8664,A,Yangon,Normal,Male,Sports and travel,85.91,5,21.4775,$451.03,8.6,Credit card,22/03/2019,02:33:00 p. m.,429.55,4.761905,21.4775
64,828-61-5674,A,Yangon,Member,Male,Sports and travel,44.02,10,22.0100,$462.21,9.6,Credit card,20/03/2019,07:57:00 p. m.,440.20,4.761905,22.0100
142,149-61-1929,A,Yangon,Normal,Male,Sports and travel,64.19,10,32.0950,$674.00,6.7,Credit card,19/01/2019,02:08:00 p. m.,641.90,4.761905,32.0950
145,882-40-4577,A,Yangon,Member,Male,Sports and travel,67.26,4,13.4520,$282.49,8.0,Credit card,19/01/2019,03:28:00 p. m.,269.04,4.761905,13.4520
161,105-31-1824,A,Yangon,Member,Male,Sports and travel,69.52,7,24.3320,$510.97,8.5,Credit card,02/01/2019,03:10:00 p. m.,486.64,4.761905,24.3320
165,765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,$457.44,6.9,Credit card,01/01/2019,10:39:00 a. m.,435.66,4.761905,21.7830

In [28]:
#Ejercicio 8
consulta8 = Super[((Super["Customer type"]) == "Member") 
                  & ((Super["City"]) == "Naypyitaw")
                  & (((Super["Payment"]) == "Cash") | ((Super["Payment"]) == "Ewallet")) ]
consulta8

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
18,360-39-5055,C,Naypyitaw,Member,Male,Sports and travel,48.91,5,12.2275,$256.78,6.6,Cash,03/09/2019,10:17:00 a. m.,244.55,4.761905,12.2275
32,784-21-9238,C,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,$10.68,5.9,Cash,02/07/2019,02:15:00 p. m.,10.17,4.761905,0.5085
33,232-16-2483,C,Naypyitaw,Member,Female,Sports and travel,68.12,1,3.4060,$71.53,6.8,Ewallet,01/07/2019,12:28:00 p. m.,68.12,4.761905,3.4060
54,835-16-0096,C,Naypyitaw,Member,Male,Sports and travel,14.70,5,3.6750,$77.18,8.5,Ewallet,24/03/2019,01:48:00 p. m.,73.50,4.761905,3.6750
61,102-06-2002,C,Naypyitaw,Member,Male,Sports and travel,25.25,5,6.3125,$132.56,6.1,Cash,20/03/2019,05:52:00 p. m.,126.25,4.761905,6.3125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,$64.00,5.9,Ewallet,18/02/2019,11:40:00 a. m.,60.95,4.761905,3.0475
941,273-84-2164,C,Naypyitaw,Member,Male,Electronic accessories,12.05,5,3.0125,$63.26,5.5,Ewallet,16/02/2019,03:53:00 p. m.,60.25,4.761905,3.0125
942,233-34-0817,C,Naypyitaw,Member,Female,Electronic accessories,98.84,1,4.9420,103.782,8.4,Cash,15/02/2019,11:21:00 a. m.,98.84,4.761905,4.9420
960,583-72-1480,C,Naypyitaw,Member,Male,Electronic accessories,37.06,4,7.4120,$155.65,9.7,Ewallet,31/01/2019,04:24:00 p. m.,148.24,4.761905,7.4120
970,325-90-8763,C,Naypyitaw,Member,Female,Electronic accessories,46.57,10,23.2850,488.985,7.6,Cash,27/01/2019,01:58:00 p. m.,465.70,4.761905,23.2850